### ISSUE TITLE
How to use this framework

### ISSUE THREAD

**Issue by NETdeve** [Myvar/CosmosGuiFramework#2]
Hello @Myvar . I am new to Cosmos and i don't know how to use (i mean to add this to references) 
your GUI Framework. Thanks in advance

**Comment by AnErrupTion** [comment]
It is very oudated, please don't use it. Instead, try to code your own controls (button, label, etc..) and use Canvas for the video driver.

**Comment by NETdeve** [comment]
Ok, thanks @AnErrupTion  i'll try to make it.
